<?php

namespace App\Pagination;


use App\Models\User;

class CustomPaginator extends \Illuminate\Pagination\Paginator
{
    /**
     * Get the instance as an array.
     *
     * @return array
     */
    public function toArray()
    {
        $countUsers = User::count();
        $pages = ceil($countUsers / $this->perPage());
        return [
            'success' => 'true',
            'page'       => $this->currentPage(),
            'total_pages'     => $pages,
            'total_users' => $countUsers,
            'count'  => $this->perPage(),
            'links' => [
                'next_url' => $this->nextPageUrl(),
                'prev_url' => $this->previousPageUrl()
            ],
            'users' => $this->items->toArray(),
        ];
    }

    protected function appendArray(array $keys)
    {
        //return parent::appendArray($keys); // TODO: Change the autogenerated stub
    }
}
